BACKGROUND_COLOR = "#B1DDC6"

WIDTH = 800
HEIGHT = 526

FRONT_IMAGE = "images/card_front.png"

CARD_WIDTH = 400
CARD_HEIGHT = 263

CARD_TITLE_WIDTH = 400
CARD_TITLE_HEIGHT = 150
CARD_TITLE_COLOR = "black"

CARD_WORD_WIDTH = 400
CARD_WORD_HEIGHT = 263
CARD_WORD_COLOR = "black"

TITLE_FONT = ("Ariel", 40, "italic")
WORD_FONT = ("Ariel", 60, "bold")
